# Generated by Django 5.0 on 2024-01-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('screenshots', models.ImageField(upload_to='project_screenshots/')),
                ('technologies_used', models.CharField(max_length=255)),
                ('project_url', models.URLField()),
                ('category', models.CharField(choices=[('django', 'Django Projects'), ('android', 'Android Projects')], max_length=50)),
            ],
        ),
    ]
