# Generated by Django 5.0 on 2024-01-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
