# Generated by Django 5.0 on 2024-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_ratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='projects/media/uploads/'),
        ),
    ]
