# Generated by Django 5.0 on 2024-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='proficiency_level',
            field=models.CharField(max_length=255),
        ),
    ]
