# Generated by Django 5.0 on 2024-01-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_project_ratingmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='facebook',
            new_name='social_media',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='linkedin',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
