# Generated by Django 5.0 on 2023-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('is_completed', models.BooleanField(default=False)),
                ('assign_date', models.DateField()),
                ('categories', models.ManyToManyField(to='Categories.category')),
            ],
        ),
    ]
