# Generated by Django 5.0 on 2024-01-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_delete_userlibraryaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
